### ISSUE TITLE
Add Front-End Spinner / Progress Bar For Large-File Attachments

### ISSUE THREAD

**Issue by huiguang-liang** [CorentinTh/enclosed#127]
### What type of request is this?

New feature idea

### As-Is
Attaching a file brings up the file selection dialog, and choosing a file. There's no front-end warning or message to indicate file limit, so the user can choose any arbitrary sized file to attached. When clicking 'create note', the website seems to freeze and the "page is not responding" browser dialog box pops up (especially for large files). After choosing to wait, the user will finally get a "file is too large" waiting and a failure to create a note event.

### To-Be
Before attaching a file, provide a by-line to indicate the configured file size limit. On creating notes, display a front-end UI progress indicator or spinner to avoid the appearance of freezing and triggering "page is not responding" browser warning.

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi @huiguang-liang 
Good point, I'll add some visual clue when encryption take some time, and some frontend limitation for the file sizes
Thanks for report :pray:

**Comment by CorentinTh** [comment]
Related to https://github.com/CorentinTh/enclosed/discussions/126
