### ISSUE TITLE
attaching files creates error

### ISSUE THREAD

**Issue by ihubgit** [CorentinTh/enclosed#139]
### Describe the bug

Running Sonoma on M1 Mac.
Tried to share a password protected note with attachment.
Getting error.

### What happened?

tried both to go to file path to get the attachment as to drag and drop it in the window.
First of all, it's not clear if something is happening when the attached file's name appears.
Does enclosed.cc work ? Does it upload the attachment ? How do I know when that's ready ?
When I tried to push the "create note" button, I'm getting an error :

> An error occurred while creating the note, please try again.

### System information

Apple Silicon M1 Max.
OS Sonoma

### Where did you encounter the bug?

Public app (enclosed.cc)

**Comment by CorentinTh** [comment]
Hi @ihubgit 
Thanks for reporting
I cannot reproduce, may be environnement related, I'll test on a mac

**Comment by ihubgit** [comment]
ok once i dropped an attachement, do I just have to wait before enclosed.cc public instance does its thing ?
When do I have to push the "create note" button ?

**Comment by CorentinTh** [comment]
You can click on `Create note` right after dropping some file, the encryption happens at the note creation time

**Comment by agalbulescu** [comment]
I'm having the same issue with a self-hosted instance on Docker, accessing the enclosed service from a mac indeed but I get this error even with a simple text note, no file attachment. The container logs don't show any errors. If I can help in any way with debugging, lmk. Thanks!

**Comment by agalbulescu** [comment]
> I'm having the same issue with a self-hosted instance on Docker, accessing the enclosed service from a mac indeed but I get this error even with a simple text note, no file attachment. The container logs don't show any errors. If I can help in any way with debugging, lmk. Thanks!

I was accessing the service straight from IP:8787, after I put it behind a reverse proxy with a ssl cert it works just fine...

**Comment by CorentinTh** [comment]
@agalbulescu  Yeah, the app need to be serve over https (see https://docs.enclosed.cc/self-hosting/troubleshooting.html#app-accessible-but-unable-to-create-a-note )

**Comment by CorentinTh** [comment]
@ihubgit which browser are you using ?
You can use `npx envinfo --system --browsers` to get all system info
