### ISSUE TITLE
[hosting] Propose to Umbrel App store

### ISSUE THREAD

**Issue by Zoobdude** [CorentinTh/enclosed#165]
https://apps.umbrel.com/

https://github.com/getumbrel/umbrel-apps/blob/master/README.md

**Comment by Zoobdude** [comment]
Of course!

**Comment by CorentinTh** [comment]
Hi @Zoobdude 

Have you had a chance to work on this issue? Let me know if you need any help.

**Comment by Zoobdude** [comment]
Currently awaiting it to be merged  https://github.com/getumbrel/umbrel-apps/pull/1563

**Comment by CorentinTh** [comment]
Oh great, thank you for the work and the PR 🤗🎉

**Comment by Zoobdude** [comment]
@CorentinTh Looks like they want the SVG version of the logo if possible, do you have this by any chance?

**Comment by Zoobdude** [comment]
And it's merged!

https://apps.umbrel.com/app/enclosed

**Comment by Zoobdude** [comment]
Will make a pr to add the link to the docs shortly

**Comment by CorentinTh** [comment]
Congrats ! Thank for PR :pray:

**Comment by CorentinTh** [comment]
To let you know @Zoobdude I've tweeted about this : https://x.com/cthmsst/status/1850833193198371022
