### ISSUE TITLE
Panic using PUBLIC_IS_AUTHENTICATION_REQUIRED

### ISSUE THREAD

**Issue by X-lem** [CorentinTh/enclosed#176]
### Describe the bug

I tried testing out the new PUBLIC_IS_AUTHENTICATION_REQUIRED. I set the **auth** env as follows. Others I left as the default

```
PUBLIC_IS_AUTHENTICATION_REQUIRED="true"
AUTHENTICATION_JWT_SECRET="[redacted]"
AUTHENTICATION_USERS="test:[redacted]"
```

### What happened?

The docker container crashed. It fails because I'm not using an email for the auth user so I'm assuming some parsing is failing somewhere and panicking. Not sure if you plan on using the email at some point (a username would be fine imo). But if you are wanting to enforce it to be an actual email for future reasons a better error message would be helpful.

![image](https://github.com/user-attachments/assets/ea9d1680-40b1-4af3-9ad5-1ecb497b5523)

### System information

Self hosting

### Where did you encounter the bug?

A self hosted instance

**Comment by CorentinTh** [comment]
I'll improve the error message, but looking at your config, I think it is because your email is not a proper email
