### ISSUE TITLE
Customize the root path when selfhosting

### ISSUE THREAD

**Issue by graphixillusion** [CorentinTh/enclosed#183]
### What type of request is this?

Hosting or Self-hosting improvement

### Clear and concise description of the feature you are proposing

As the title says, is it possible to configure where is the root of the service? I already tried with this env var but it doesn't seems to work as intended:

SERVER_CORS_ORIGINS="https://web.site/custompath/enclosed/"

Like this it doesn't load any resources as it always looks for them in https://web.site/api/config

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi @graphixillusion 

Just added the env variable `PUBLIC_BASE_API_URL` en variable in #211, available in the v1.6.8/latest version of enclosed.
It permits to configure the base URL of the api, it can be an absolute URL (like `https://example.com/enclosed`) or a path (like `/enclosed`)

So you can no retry with `PUBLIC_BASE_API_URL=web.site/custompath/enclosed`

**Comment by graphixillusion** [comment]
I've just tried this but this seems to work just for the api. The other resources path are not reflected so if the  the PUBLIC_BASE_API_URL=web.site/custompath/enclosed, i'm not having anymore the api error but the site is not loading becouse it wants assets and other thigs from web.site/assets/blabla and web.site/site.webmanifest while it should looks in
web.site/custompath/enclosed/assets/blabla and web.site/custompath/enclosed/site.webmanifest
