### ISSUE TITLE
AUTHENTICATION_USERS does not work

### ISSUE THREAD

**Issue by thokich** [CorentinTh/enclosed#188]
hey,
i have find your Application by YouTube-DB Tech and i have test it.

Sorry but the funktion AUTHENTICATION_USERS does not work.

my docker compose file is:

services:
  enclosed:
    image: corentinth/enclosed:1.6.3
    container_name: enclosed
    ports:
      - 8787:8787
    volumes:
      - /mnt/enclosed/data:/app/.data
    environment:
      - SERVER_CORS_ORIGINS=https://xxx.yy
      - AUTHENTICATION_USERS=/*User Authentication Key Generator*/
      - AUTHENTICATION_JWT_SECRET=change_me
      restart: unless-stopped

I have no logon.

**Comment by CorentinTh** [comment]
Hello @thokich, you have to set the env variable PUBLIC_IS_AUTHENTICATION_REQUIRED to true to enable authentication 

See here https://docs.enclosed.cc/self-hosting/configuration

**Comment by thokich** [comment]
Hy, thanks for your fast help.
sometimes you can't see the forest for the trees.
It's a german saying.
I will see what nice features you will add in feature.
Thx from Germany
