### ISSUE TITLE
Implement Logon with 2FA

### ISSUE THREAD

**Issue by thokich** [CorentinTh/enclosed#189]
### What type of request is this?

New feature idea

### Clear and concise description of the feature you are proposing

Hello,
to increase security when logging in, you could implement two-factor authentication (2FA). You can also log in from a different computer without the login being fished.

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi @thokich,
Thank you for your suggestion. At the moment, we do not have plans to implement 2FA, as the scope of authenticated user actions is currently limited to creating notes, which carries a low security risk.

If we decide to expand security features, including 2FA, I'll be sure to revisit and reopen this issue.
