### ISSUE TITLE
413 Payload Too Large Error 

### ISSUE THREAD

**Issue by DocksToBox** [CorentinTh/enclosed#238]
### Describe the bug

We are encountering a 413 Payload Too Large error when sending POST requests to the /api/notes endpoint. The error appears even when the request body is relatively small (e.g., 81 bytes). This suggests that the application may have a strict limit on the payload size, which could be causing this issue.

### What happened?

**Here is the relevant log output from the server:**
`{
    "level": 50,
    "time": 1727683750804,
    "pid": 1,
    "hostname": "5179ee91e60d",
    "namespace": "middlewares:error",
    "error": {
        "code": "note.payload_too_large",
        "cause": {},
        "statusCode": 413,
        "isCustomError": true
    },
    "msg": "Note payload is too large"
}
`
The error is consistently triggered whenever a POST request is made to the /api/notes endpoint, even with a minimal payload size. Here is a log sample of the request and response cycle:
`{
    "level": 30,
    "time": 1727683750805,
    "pid": 1,
    "hostname": "5179ee91e60d",
    "namespace": "app",
    "status": 413,
    "method": "POST",
    "path": "/api/notes",
    "routePath": "/api/notes",
    "durationMs": 238,
    "msg": "Request completed"
}
`
**Steps to Reproduce:**

1. Send a POST request to the /api/notes endpoint with a payload size of approximately 81 bytes or more.

2. Observe the response, which returns a 413 Payload Too Large error.
**Expected Behavior:**
The server should accept the request and process the payload without returning a 413 Payload Too Large error, especially for relatively small payloads.
**Additional Information:**
The issue seems to be related to the backend's configuration, potentially caused by a middleware that restricts the request body size.
The current setup is behind an Nginx proxy with client_max_body_size set to a large value (e.g., 102400m). Thus, we believe this issue is isolated to the application layer rather than the proxy layer.
**Request:**
Please review the backend middleware or configuration responsible for handling request payloads and increase the allowed payload size for the /api/notes endpoint. If applicable, consider increasing the default request size limit across the entire application or making it configurable.
**Additional Considerations:**
If the application intentionally limits the payload size for security reasons, could you provide guidance on an alternative approach, such as handling larger payloads via a file upload mechanism or splitting requests into smaller chunks?

Thank you for your attention to this matter.

### System information

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 8.25 GB / 15.87 GB
  Browsers:
    Edge: Chromium (128.0.2739.63)
    Internet Explorer: 11.0.19041.4355

### Where did you encounter the bug?

Other (installations, docker, etc.)

**Comment by CorentinTh** [comment]
Hi @DocksToBox 

The upload limit is, by default really big : 50Mib for the whole encrypted note, see on the public instance : https://enclosed.cc

You can change the limit by setting the env variable `NOTES_MAX_ENCRYPTED_PAYLOAD_LENGTH` to a bigger number, here is the documentation : https://docs.enclosed.cc/self-hosting/configuration

**Comment by DocksToBox** [comment]
I sincerely apologize for my oversight and the inconvenience it has caused
you. I'm truly sorry. Your project is excellent!

Corentin THOMASSET ***@***.***> 于2024年9月30日周一 17:14写道：
