### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by grosbedos** [CorentinTh/enclosed#239]
### Describe the bug

Hello,

Is it possible to display line breaks when viewing a note?

I have not been able to do this. (with br, or backslash n, or pre)

### What happened?

I don't know if it's a bug or a feature

### System information

I can't get this information from the container. But I've taken the latest image.

### Where did you encounter the bug?

A self hosted instance

**Comment by CorentinTh** [comment]
Related to #228

**Comment by grosbedos** [comment]
Thanks a lot, i was on 1.6.8.

It's perfect with 1.6.9.

Best regards.
