### ISSUE TITLE
URL Scanners will mark note as read.

### ISSUE THREAD

**Issue by CorneliousJD** [CorentinTh/enclosed#240]
### Describe the bug

The note will be marked as read if a URL scanner (such as many business e-mail security tools) scan the URL.

Implementing a "reveal note" button prior to revealing contents and marking it as read like many other tools in this category would be great!

### What happened?

Sending a url through an e-mail with a business e-mail scanner will cause it to be marked as read.

### System information

N/A

### Where did you encounter the bug?

Public app (enclosed.cc)

**Comment by CorentinTh** [comment]
Hi @CorneliousJD 

It's a good point, I'll add a reveal button :+1:

**Comment by CorentinTh** [comment]
Thanks for reporting the issue. A prompt has been added to reveal the note if it has been marked for deletion after reading.

![image](https://github.com/user-attachments/assets/f4858db8-791c-48ae-895c-b6c583aaaab9)
