### ISSUE TITLE
Allow to configure default value for `Delete after reading`

### ISSUE THREAD

**Issue by dinhhuy258** [CorentinTh/enclosed#247]
### What type of request is this?

Enhancement of an existing feature

### Clear and concise description of the feature you are proposing

Currently the `Delete after reading` value is off by default when creating secret. I would like this to be configurable via the environment so that we can change the default behavior when creating a secret.

<img width="1323" alt="image" src="https://github.com/user-attachments/assets/104800f4-7836-4a6a-aa23-975235f81906">

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi @dinhhuy258 

Thank you for the request :pray: 
I added an env variable `PUBLIC_DEFAULT_DELETE_NOTE_AFTER_READING` to configure the default state of the `Delete after reading` button, by default at `false`

You can add `PUBLIC_DEFAULT_DELETE_NOTE_AFTER_READING=true` to your config

More details here: https://docs.enclosed.cc/self-hosting/configuration

It's available in the latest >=`1.7.1` version

**Comment by dinhhuy258** [comment]
thank you  🚀
