### ISSUE TITLE
How to deploy using Cloudflare Pages?

### ISSUE THREAD

**Issue by huawuhen** [CorentinTh/enclosed#258]
### What type of request is this?

New feature idea

### Clear and concise description of the feature you are proposing

How to deploy using Cloudflare Pages?

### Additional context

How to deploy using Cloudflare Pages?

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi @huawuhen,

To deploy this project to Cloudflare Pages using their continuous deployment pipeline, follow these steps:

1. **Fork the Repository**  
2. **Set Up a New Cloudflare Pages Project**  
   - In the Cloudflare Pages dashboard, create a new project and link it to your forked repository.
   - When prompted, set the deployment to target a subfolder within the repo: [`packages/deploy-cloudflare`](https://github.com/CorentinTh/enclosed/tree/main/packages/deploy-cloudflare).
3. **Configure Build Settings**  
   - **Build Command**: `pnpm build`
   - **Output Directory**: `dist`

Once you've set this up, Cloudflare Pages will handle the rest
Let me know if you encounter any issues!

**Comment by cy920820** [comment]
@CorentinTh  

KV error

![Image](https://github.com/user-attachments/assets/eb32fa60-abbb-433f-a4d9-da810dcb475c)

**Comment by CorentinTh** [comment]
Please update your KV key in `wrangler.toml`

**Comment by cy920820** [comment]
> Please update your KV key in `wrangler.toml`

good, thank you

**Comment by cy920820** [comment]
How to set this variable `NOTES_MAX_ENCRYPTED_PAYLOAD_LENGTH` on cloudflare pages  @CorentinTh
