### ISSUE TITLE
Add QR code of links

### ISSUE THREAD

**Issue by neexa** [CorentinTh/enclosed#274]
### What type of request is this?

New feature idea

### Clear and concise description of the feature you are proposing

Seeing QR code of generated links for fast copy to phones would be a nice feature

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi @neexa, good idea, I'll add qrcodes :pray:

**Comment by CorentinTh** [comment]
Hi @neexa, I added a qr-code card when not is created in #282, it's available on public instance and dockers image version `1.8.0`

![screenshot-2024-10-15-23-49-47](https://github.com/user-attachments/assets/7e7eda91-92d0-4205-8dcc-a8a18c8f7747)

**Comment by neexa** [comment]
Fantastic 👍👍👍
