### ISSUE TITLE
Docker image build hang for arm/v7

### ISSUE THREAD

**Issue by CorentinTh** [CorentinTh/enclosed#314]
Related to #312 

The build of the image hangs for armv7 on node:22-alpine image, it's a known issue (https://github.com/nodejs/docker-node/issues/2077)

It seems to work with non-alpine images (like node:22-slim), I'm testing to have a multi-stage Dockerfile to build on non-alpine and release on alpine

**Comment by Zoobdude** [comment]
Sorry to cause such a headache. Thanks for trouble shooting though 😅

**Comment by CorentinTh** [comment]
No problem @Zoobdude :v:

**Comment by Zoobdude** [comment]
Thanks very much @CorentinTh :D
