### ISSUE TITLE
Error 500 when trying to upload a 30mb file to public instance

### ISSUE THREAD

**Issue by Zoobdude** [CorentinTh/enclosed#337]
### Describe the bug

I attempted to upload a 30mb file (should be below file limit) to the public enclosed.cc instance which fails with a error 500.

### What happened?

I generated a 30 mb file using [Powershell fsutil](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil): `fsutil file createnew ./30mb.txt 30000000`

![image](https://github.com/user-attachments/assets/a6b85ce9-7201-4e54-b707-43436645ceee)

Then attempted to upload to the public instance and received this error:

![image](https://github.com/user-attachments/assets/f2167980-e171-44f1-bccf-ed46705ae59b)
![image](https://github.com/user-attachments/assets/792a7e28-b1e0-4098-b9ef-1736b1c15159)

This is not the expected 413 (Payload Too Large) error if the uploaded file is too large.

When testing in a local development environment this is not an issue and the same 30 mb file uploads successfully. 

### System information

Windows 10
Chrome Version 130.0.6723.117 (Official Build) (64-bit)

### Where did you encounter the bug?

Public app (enclosed.cc)

**Comment by CorentinTh** [comment]
The 413 Error handling has been corrected in #342

Thanks for the report :pray:
