### ISSUE TITLE
If there are large files, then the page takes a long time to load completely

### ISSUE THREAD

**Issue by DocksToBox** [CorentinTh/enclosed#339]
### What type of request is this?

Enhancement of an existing feature

### Clear and concise description of the feature you are proposing

I find that if I want to send someone an Enclosed containing a very large file, I can see in F12 that it has been transferring the file, but there is no visual indication on the web page if there is a problem or if it is waiting to be transferred, and the display of my web page remains blank until the transfer is completely finished, which I feel creates a great deal of frustration for the person I want to receive it from. But I don't think it's a bug, I think it's a point that can be improved upon

### Additional context

![PixPin_2024-11-15_10-09-25](https://github.com/user-attachments/assets/daf7118c-df0c-4cd7-b026-fac5fe4f4de8)

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi @DocksToBox 
Added a loading state while fetching and decrypting note in #350 
Thanks for the report :pray: 

![image](https://github.com/user-attachments/assets/fdccf150-9b29-4a58-9c40-4426c194e50d)
