### ISSUE TITLE
Detect browser language

### ISSUE THREAD

**Issue by SamKr** [CorentinTh/enclosed#343]
### What type of request is this?

New feature idea

### Clear and concise description of the feature you are proposing

Is it possible to have Enclosed detect the browser's language, and if it's present as a translation, automatically select it? And if not found, default to English.

### Additional context

This would enhance the usability for non-technical users not fluent in English. I've tried a few browsers, but doesn't seem like that's how it currently functions, unless I made a mistake.

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi @SamKr 

This is actually already the case
The app detects your preferred browser language and, if a matching translation is available, it automatically selects it. If no match is found, it defaults to English.

However, if you manually switch to another language, your choice is persisted in local storage. This ensures that the next time you visit, the app remembers your selected language.

To test this behavior, you can either clear your browser's local storage or open the app in incognito mode.

The code for this logic is in [i18n.provider.tsx](https://github.com/CorentinTh/enclosed/blob/main/packages/app-client/src/modules/i18n/i18n.provider.tsx#L44) file.
Related to #338

**Comment by SamKr** [comment]
You are absolutely right, sorry! Even though the browser was in Dutch, the preferred language was English. Tested with both set to Dutch and it's working like a charm. 

Thanks for the quick and extensive reply.
