### ISSUE TITLE
Allow delete after being read upto # times 

### ISSUE THREAD

**Issue by jameslmoss** [CorentinTh/enclosed#349]
### What type of request is this?

Enhancement of an existing feature

### Clear and concise description of the feature you are proposing

Instead of just an on|off toggle, being able to set a number of times (user input) to read so it burns/deletes only after being read that number of times.

![delete-after-reading-1](https://github.com/user-attachments/assets/14ed5e43-5fce-4da0-8679-d13bd59d9ac8)

Not dire as it's great as it is, but would add extra flexibility in how it can be used.

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi @jameslmoss 
Thank you for your suggestion. It's a good idea, but I don't think it will be implemented in Enclosed. I want to keep the app as simple as possible, and I don't really see the added value of this feature, either you want the note to be read only once or you want it to be read multiple times, I'm not sure what the use case would be for a note that can be read like 3 times and then self-destruct

If you have any other suggestions or questions, feel free to ask!

**Comment by jameslmoss** [comment]
Thanks and no worries, I get wanting to keep it simple. 

As for Use cases, think lotteries/giveaways share into a group chat, first 10 ppl to open it get to view it burns after x num.
That combined with timed burns could be handy in some situations. 
Also families or just any situation where you wanna share something a fixed number of times lets say to your phone + laptop or  whatever. 

It's kind of similar to a timer/timeout, just a different way to go about it and could be combined with a timer/timeout burn.
