### ISSUE TITLE
File upload via CLI

### ISSUE THREAD

**Issue by Zoobdude** [CorentinTh/enclosed#357]
### What type of request is this?

Enhancement of an existing feature

### Clear and concise description of the feature you are proposing

It looks like when file upload was added to the website, it wasn't also added to the CLI.

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Yeah good point, I'll work on that, adding some `--file / -f` flag to attach files
