### ISSUE TITLE
Environment variables deployed with Cloudflare Pages do not take effect

### ISSUE THREAD

**Issue by dishao123** [CorentinTh/enclosed#362]
### Describe the bug

I configured the following environment variables, but found that they were not effective

`AUTHENTICATION_JWT_SECRET`
`AUTHENTICATION_USERS`
`PUBLIC_IS_AUTHENTICATION_REQUIRED`
`PUBLIC_IS_SETTING_NO_EXPIRATION_ALLOWED`

Then visit https://enclosed-bvn.pages.dev/

Found that the `Never expire` option was not displayed on the page, and the `Authentication` function was not effective

Please help, thank you

### What happened?

This is a screenshot of the environment variables from the Cloudflare dashboard
![Cloudflare-Web-Performance-Security-11-28-2024_06_19_PM](https://github.com/user-attachments/assets/4c390cd7-2fb7-46cf-aa07-ac1a9304d092)

This is a screenshot of the `enclosed` webpage
![Enclosed-Send-private-and-secure-notes-11-28-2024_06_20_PM](https://github.com/user-attachments/assets/e3d19a11-393c-4563-927f-3f98a03f7d1f)

### System information

Deployment environment: `Cloudflare Pages`
Build command: `pnpm build`
Output directory: `dist`
Build directory: `packages/deploy-cloudflare`
Configuration file：[wrangler.toml](https://github.com/dishao123/enclosed/blob/main/packages/app-server/wrangler.toml)

### Where did you encounter the bug?

A self hosted instance

**Comment by dishao123** [comment]
> Hi @dishao123
> 
> When deploying on Cloudflare, the server does not inject its public configuration into the client (the **runtime config**) as the node version would do. To address this, you'll need to set **build-time configuration** variables when building the client
> 
> ```shell
> VITE_IS_AUTHENTICATION_REQUIRED=true
> VITE_IS_SETTING_NO_EXPIRATION_ALLOWED=true
> ```
> 
> You can find more information about build-time variables here: https://github.com/CorentinTh/enclosed/blob/main/packages/app-client/src/modules/config/config.constants.ts
> 
> I understand this is not ideal. We'll work on simplifying this process to create a single source of truth for configuration, and/or had some documentation

Hello, what file do I need to modify to make the environment variables take effect normally?

**Comment by CorentinTh** [comment]
It depends on how you build and deploy to CF, either in the Page Deployement pipeline UI if you use CF Pages app, or in your github CI build env if you manually deploy from your CI

**Comment by cy920820** [comment]
> It depends on how you build and deploy to CF, either in the Page Deployement pipeline UI if you use CF Pages app, or in your github CI build env if you manually deploy from your CI

Is it modified in the wrangler.toml file?

**Comment by ramithuh** [comment]
If anyone comes across this issue, i setup the env variables like this and it worked 

```
name = "enclosed-app"
compatibility_date = "2024-08-20"
pages_build_output_dir = "./dist"

# Define variables for the production environment
[env.production.vars]
VITE_IS_SETTING_NO_EXPIRATION_ALLOWED = "true"
VITE_DEFAULT_NOTE_NO_EXPIRATION = "true"

# Define KV bindings for the production environment
[[env.production.kv_namespaces]]
binding = "notes"
id = "<REPLACE>"
```
