### ISSUE TITLE
File upload and host memory

### ISSUE THREAD

**Issue by grosbedos** [CorentinTh/enclosed#366]
### Describe the bug

Hi,

I would like to upload big file with a note (1Go).
I have modified NOTES_MAX_ENCRYPTED_PAYLOAD_LENGTH to support this.

### What happened?

My container is always killed by OOM killer. (no more memory left on the host)

Do I need as much free memory as the size of the file I'm uploading?

Best regards

### System information

Enclosed v1.11.0
Debian 12.7
Docker version 27.3.1, build ce12230

**Comment by CorentinTh** [comment]
I’m closing this as not planned for now. We’ll make sure to mention you if we decide to address this differently in the future :pray:
