### ISSUE TITLE
enable HTTPS without reverse proxy

### ISSUE THREAD

**Issue by fanyangto** [CorentinTh/enclosed#371]
### What type of request is this?

Enhancement of an existing feature

### Clear and concise description of the feature you are proposing

I am generally familiar with openssl and PKI operations to create server certs. Is there a way/documentation on how to enable HTTPS on Enclosed app without putting a reverse proxy in front of it ? I find the documentation lacking in this regard. We probably need a few pointers on how to do this, and we can run along on our own. 

Ideally, the Enclose app should support HTTPS on its own, with the cert/keystore passed in to the docker environment. It could even deploy a self-signed cert, until the user has the time to replace it with a proper cert chain. 

This would be so much better than upon the first docker deployment, the page is basically unusable due to the lack of HTTPS. 

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hey @fanyangto 

Just added native HTTPS support in #376 

You can see the added configuration variable in the [config page](https://docs.enclosed.cc/self-hosting/configuration), and a dedicated explanation here: https://docs.enclosed.cc/self-hosting/configuration#optional-native-https-configuration

**Comment by fanyangto** [comment]
hi, @CorentinTh 

Please update the documentation on how to pass the cert/key files to the docker. It wasn't clear in the document whether the env vars are paths to the key and the cert, or the key and paths itself. I think many people will struggle. I do the following in the command line. 

`docker run -d --restart unless-stopped -p 8787:8787 \
--user $(id -u):$(id -g) -v ~ubuntu/config:/app/.data \
-e SERVER_USE_HTTPS=true -e SERVER_HTTPS_KEY="$(cat ~ubuntu/config/private-key.pem)" \
-e SERVER_HTTPS_CERT="$(cat ~ubuntu/config/certificate.pem)" \
corentinth/enclosed:latest-rootless`
