### ISSUE TITLE
need a setting to remove the recipient's ability to send notes

### ISSUE THREAD

**Issue by fanyangto** [CorentinTh/enclosed#378]
### What type of request is this?

New feature idea

### Clear and concise description of the feature you are proposing

Perhaps I have missed it. I noticed the recipient's page will have a SendNote button. While this maybe useful in some cases, it can be problematic. For example, if A sends a note to B. It doesn't want B has the ability to send a note to C, or D and so on.  This doesn't mean we need authentication to control the access to the system, just have some form of controls what the recipient can and can not do. 

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi @fanyangto :wave: 
You can enable and enforce authentication for note creation using the `PUBLIC_IS_AUTHENTICATION_REQUIRED` env variable and use `AUTHENTICATION_USERS` to setup your users (currently their is no "register" page)

Look for authentication related config in the docs here : https://docs.enclosed.cc/self-hosting/configuration

Maybe authentication deserve a dedicated "recipe" page :thinking:
