### ISSUE TITLE
Permission issue /app/.data/

### ISSUE THREAD

**Issue by zarevskaya** [CorentinTh/enclosed#59]
Hello,
 I tested your application but I encountered this problem. Do you have any advice for me? 

namespace=middlewares:error error={"errno":-13,"code":"EACCES","syscall":"open","path":"/app/.data/01j6hpbg7d178vvsvq17qgm1v8"} msg=EACCES: permission denied, open '/app/.data/01j6hpbg7d178vvsvq17qgm1v8'

Thanks!

**Comment by CorentinTh** [comment]
Oh thanks for the report, it's due to the [recent update](https://github.com/CorentinTh/enclosed/commit/8e2ab684536188037ec9bd6060af5b982884a65d) to run the docker as non-root, I'll fix that

**Comment by CorentinTh** [comment]
It has been fixed and released, it should fork fine on latest (1.3.1) docker image

**Comment by CorentinTh** [comment]
@zarevskaya 
It has been fixed and released, it should fork fine on latest (1.3.1) docker image
Thanks again for the report

**Comment by zarevskaya** [comment]
Merci ;)
