### ISSUE TITLE
[FEAT] Smaller note links

### ISSUE THREAD

**Issue by starsoccer** [CorentinTh/enclosed#61]
More of a usability request, but it would be great if there was a way to make links to notes significantly smaller more on the length of pastbin or privnote. For copy/pasting the current link there is no issue, but in cases where a link has to be typed, its quite long

**Comment by CorentinTh** [comment]
Thanks for the suggestion!
The thing is, with Enclosed, the e2e encryption key is part of the URL to make sure everything stays secure and only the recipient can read the note. If we made the URLs shorter, we’d have to either cut down on the encryption key or leave it out, which would really weaken the security.

I know the long URLs can be a pain to type out, but keeping everything secure is the top priority. We’ll keep thinking about ways to improve this, but for now, it’s a bit tricky.

Thanks for understanding!

**Comment by nullptrx** [comment]
Could we consider adding a URL shortening feature with a 302 redirect to the long URL?

**Comment by Zoobdude** [comment]
That would mean storing the long URL (which contains the encryption key) on the server therefore no longer making it e2e

**Comment by CorentinTh** [comment]
As @Zoobdude mentioned, storing the complete note URL, including the encryption key, on a URL shortener service compromises the note's security. Anyone with access to the shortener’s backend could view the URL (especially if no password is applied), potentially exposing sensitive information.

We can also propose a "less-secure" mode with shorter encryption key, but I'm not sure it's a path we are willing to follow
