### ISSUE TITLE
[docs] Normalize doc theme to match app design

### ISSUE THREAD

**Issue by CorentinTh** [CorentinTh/enclosed#75]
- [ ] Use the same [tabler icons](https://icones.js.org/collection/tabler) as the app
- [ ] Normalize colors

**Comment by Zoobdude** [comment]
Happy to have this one assigned to me.

**Comment by CorentinTh** [comment]
@Zoobdude ok no problem, I let you have a look at [vitepress.dev](https://vitepress.dev/) to manage the themes

**Comment by Zoobdude** [comment]
Do you want all the components re-written that use icons? Or just swap the social (gh and x) icons in the corner?

**Comment by CorentinTh** [comment]
Just swaping the icons is good :ok_hand:
