### ISSUE TITLE
[hosting] Propose to runTipi

### ISSUE THREAD

**Issue by CorentinTh** [CorentinTh/enclosed#88]

**Comment by johnnyq** [comment]
hi @CorentinTh do you know when enclosed will get added to runtipi?

**Comment by CorentinTh** [comment]
Hi @johnnyq, no idea, the PR is idling on runtipi side :shrug:

**Comment by CorentinTh** [comment]
They no longer accept new apps for now, see https://github.com/runtipi/runtipi-appstore/pull/4924#issuecomment-2549496581

I'm closing, we'll reopen if their's some changes
