### ISSUE TITLE
Add to awesome-selfhosted

### ISSUE THREAD

**Issue by CorentinTh** [CorentinTh/enclosed#90]
Add to https://github.com/awesome-selfhosted/awesome-selfhosted

**Comment by Zoobdude** [comment]
Looks like the earliest this can be done is `13/12/2024`.

Happy to have this assigned to me

**Comment by CorentinTh** [comment]
It may also be added to others "awesome-ish" repository related to FOSS/self-hosting if you find some

**Comment by CorentinTh** [comment]
Hi @Zoobdude 

Have you had a chance to work on this issue? 
Let me know if you need anything.

**Comment by Zoobdude** [comment]
Currently waiting till December 13th

Going to propose to this - https://github.com/Atarity/deploy-your-own-saas

Have you got any other lists in mind?

**Comment by Zoobdude** [comment]
Will be making the PR tomorrow!

**Comment by CorentinTh** [comment]
Nice :fire:  thank you! :pray:

**Comment by Zoobdude** [comment]
And it's live! https://awesome-selfhosted.net/index.html#enclosed

**Comment by CorentinTh** [comment]
Nice!
Thanks again
